export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_ONE_CATEGORY = 'DELETE_ONE_CATEGORY';
export const UPDATE_ONE_CATEGORY = 'UPDATE_ONE_CATEGORY';

export const GET_ALL_BRAND = 'GET_ALL_BRAND';
export const GET_ONE_BRAND = 'GET_ONE_BRAND';
export const CREATE_BRAND = 'CREATE_BRAND';
export const DELETE_ONE_BRAND = 'DELETE_ONE_BRAND';
export const UPDATE_ONE_BRAND = 'UPDATE_ONE_BRAND';

export const CREATE_SUB_CATEGORY = 'CREATE_SUB_CATEGORY';
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY';
export const GET_ALL_SUB_CATEGORY = 'GET_ALL_SUB_CATEGORY';
export const DELETE_ONE_SUB_CATEGORY = 'DELETE_ONE_SUB_CATEGORY';
export const GET_ONE_SUB_CATEGORY = 'GET_ONE_SUB_CATEGORY';
export const UPDATE_ONE_SUB_CATEGORY = 'UPDATE_ONE_SUB_CATEGORY';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_PRODUCTS_CATEGORY = 'GET_ALL_PRODUCTS_CATEGORY';
export const GET_ALL_PRODUCTS_BRAND = 'GET_ALL_PRODUCTS_BRAND';
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS';
export const GET_PRODUCT_LIKE = 'GET_PRODUCT_LIKE';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const VERIFY_PASSWORD = 'VERIFY_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';

export const CREATE_REVIEW = 'CREATE_REVIEW';
export const ALL_REVIEW_PRODUCT = 'ALL_REVIEW_PRODUCT';
export const DELETE_REVIEW_PRODUCT = 'DELETE_REVIEW_PRODUCT';
export const UPDATE_REVIEW_PRODUCT = 'UPDATE_REVIEW_PRODUCT';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const GET_ALL_WISHLIST_USER = 'GET_ALL_WISHLIST_USER';

export const ADD_NEW_COUPON = 'ADD_NEW_COUPON';
export const GET_ALL_COUPON = 'GET_ALL_COUPON';
export const GET_ONE_COUPON = 'GET_ONE_COUPON';
export const DELETE_ONE_COUPON = 'DELETE_ONE_COUPON';
export const UPDATE_ONE_COUPON = 'UPDATE_ONE_COUPON';

export const CREATE_USER_ADDRESS = 'CREATE_USER_ADDRESS';
export const UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS';
export const DELETE_USER_ADDRESS = 'DELETE_USER_ADDRESS';
export const GET_ALL_USER_ADDRESS = 'GET_ALL_USER_ADDRESS';
export const GET_ONE_USER_ADDRESS = 'GET_ONE_USER_ADDRESS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const ALL_IN_CART = 'ALL_IN_CART';
export const DELETE_ALL_CART_ITEMS = 'DELETE_ALL_CART_ITEMS';
export const DELETE_ONE_CART_ITEM = 'DELETE_ONE_CART_ITEM';
export const UPDATE_ONE_CART_ITEM = 'UPDATE_ONE_CART_ITEM';
export const APPLY_COUPON_CART = 'APPLY_COUPON_CART';

export const CREATE_ORDER_CASH = 'CREATE_ORDER_CASH';
export const CREATE_ORDER_CARD = 'CREATE_ORDER_CARD';
export const GET_USER_ALL_ORDERS = 'GET_USER_ALL_ORDERS';
export const GET_USER_ONE_ORDER = 'GET_USER_ONE_ORDER';
export const UPDATE_ORDER_PAY = 'UPDATE_ORDER_PAY';
export const UPDATE_ORDER_DELIVER = 'UPDATE_ORDER_DELIVER';

export const GET_ERROR = 'GET_ERROR';
